use_frameworks!

target 'ZXSCocoaPods_Example' do
  pod 'ZXSCocoaPods', :path => '../'

  target 'ZXSCocoaPods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
